### ISSUE TITLE
WGLC: Fix penultimate para of S3.2

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/multipart-ct#10]
Include one more byte for the CBOR array.

**Comment by cabo** [comment]
?

**Comment by thomas-fossati** [comment]
Copied from the WGLC thread:

>> 3.2 "In effect, the serialization for a single object is done by
>> prefixing the object with information about its content-format (here:
>> 0x82 0x00) and its length (here: 0x4b)." -- What about the array
>> containing the two elements?
> 
> Sorry, I don’t understand this.

Klaus points out that there is one more byte, something like 0x81.

**Comment by cabo** [comment]
Er, the 0x82 is right there.  Maybe that is not strictly enough "information about its content-format".

... with information that there is one object (here: 0x82), about its content-format (here:
0x00) and its length (here: 0x4b)."

**Comment by thomas-fossati** [comment]
LGTM; close?

**Comment by cabo** [comment]
What lgty: the existing text or the update I proposed above.

**Comment by thomas-fossati** [comment]
the latter
