### ISSUE TITLE
WGLC: Change "Fragment identifier considerations" as CBOR's

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/multipart-ct#11]
Carsten adds:
> Should we also copy the text: “(At
>     publication of this document, there is no fragment identification
>     syntax defined for “application/cbor”.)"
> ?

**Comment by cabo** [comment]
Yes.

(Where is the rest of that change?)

**Comment by thomas-fossati** [comment]
As we speak there's no PR, only this issue.

**Comment by thomas-fossati** [comment]
@cabo would you mind writing the missing text?  I'm not comfortable messing around with media type registration procedures :-)
