### ISSUE TITLE
WGLC: Say how a receiver handles syntactically invalid application/multipart-core representations

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/multipart-ct#6]
Klaus:
> There should be a sub-section or paragraph specifying what a
> recipient of a application/multipart-core representation should do if
> it encounters something that doesn't match the grammar. Does the whole
> array become unusable when there is an unexpected element, or can a
> recipient use the array up to the unexpected element? Should a
> recipient try to do error recovery and skip to the next element? This
> has impact on how the format can be evolved in the future.

Carsten seems to prefer failing hard and early (draft-iab-protocol-maintenance).

Thomas loves simplicity and +1 Carsten's proposal.

**Comment by cabo** [comment]
Klaus has a point, but we already have a way to evolve: Define a new media type.  I don't think there really is a need here to haphazardly send a new version of this to someone that might not understand it.

**Comment by thomas-fossati** [comment]
+1, as I said in other emails, we don't need to make it perfect now.  Let's make it simple, use it and measure its ergonomics.  We can always grab another code point in the future it this needs fixing.

**Comment by thomas-fossati** [comment]
@ektrah wdyt?

**Comment by thomas-fossati** [comment]
sorry, hit the wrong button
