### ISSUE TITLE
WGLC: The fate of the PubSub example

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/multipart-ct#8]
Klaus:
> I see that draft-ietf-core-coap-pubsub-05 is still proposing a
> new response code (2.07) for this scenario. Will -pubsub switch to
> -multipart-ct as described in this section? If not, better remove the
> example.

**Comment by thomas-fossati** [comment]
Added the "question" label: we need an answer from pubsub authors about their intentions.

Or, alternatively, we could just remove the example.

**Comment by cabo** [comment]
After the interim meeting yesterday, it does not look like pubsub *needs* multipart-core.
But an application of pubsub could use it, so I think we just need to update the example not to claim this is a part of core pubsub.  (And it looks to me we did this already?)

**Comment by thomas-fossati** [comment]
Yesterday's interim has cleared the question label on this issue which can be IMO closed without action.

**Comment by cabo** [comment]
OK
